[litex]
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "c4e635ea5c91caecd5bb1f4182dc36c1f766085c"

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "bf458e388efea428189a4a33c1cb40cadce85d48"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "6cf7759c9bfaf221eec6e62cae504c7e88ab690b"

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "3d066c87f948e3f8584dfa0244d0930161f71e62"

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "76454e4c0c304a34b9915722de750887c3abbe89"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "04aa1396f500418dbcbb15f5afb08eaf01a9e8d9"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "b4f3f2148e6d554d2f4c1d3ab30af3757eaf8de5"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "1d7e91d019ed2b9fff56485995a7d0d16b45c21b"

[litesdcard]
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "3750889e1473f649ff3d3142f3e3978c00cc53a8"

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "28a17d801d588f1cd43ac8c38b98faa603eba45e"

[litevideo]
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-cpu-vexriscv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv"
git_revision = "e789d50ed1f2a014841e6a8b5f50c714aca3b241"

[pythondata-cpu-vexriscv_smp]
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv_smp"
git_revision = "4306ae2eb5464bc37d14eff9a3c051d7b0c17d0d"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "fbcb02422940bbb97c492f0c970959d262b33632"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "45b8f0d208e5bd717d973a07fd9f72ea8a91902a"

[pythondata-software-picolibc]
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "393d106c6e9b8fdd115a0a301f3a6c0478f92f3b"

[valentyusb-hw_cdc_eptri]
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "0b534ccfccfcdcb7a5db219743f0c0b20e5ec412"
git_branch = "hw_cdc_eptri"
