[litex]
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "05b960d09bc7032adb97c404d28c1d7423a84d28"
github_archive_nix_hash = "051p504ipb4rvz3vgl8znqi55hga0n3bz0a624x4yv6a76x1sjj2"

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "67756e53ae0b039b78c904dee4c40ff667ab24cc"
github_archive_nix_hash = "11lg0g062rzdicirrg2xqqf3r5l9vwxpjxi4ldbgmfjd06inshga"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "e39fec240b05f66f9592c24ea2c2aa7f5434efea"
github_archive_nix_hash = "1mmwxcxg36pwpxh1brmpxkqc20j12yws09lcqs9x16ry0ph8yibx"

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "e9a4a746e93af186695f00e72f035a7892e9212e"
github_archive_nix_hash = "0v3y7wdirxvqygsg9z0bb2gkc6408dfwynm39lhgwsnqhwds3gq5"

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "9f118e83c819a20e1348d295cc9a251cc006f8f8"
github_archive_nix_hash = "0sziiqjs1z526zv9zrf5mpgf8inw7pqycrk6538srza9818bgdr9"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "3d8ecdbcf9f0260292221ff63b0ad3f5e409a955"
github_archive_nix_hash = "0blvgg26pf174nl8gi91a3aahalav0l4fcqdyphhc2i49iz63rnr"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "589815cb318ee15c7ce1422bd606e5b561a9d608"
github_archive_nix_hash = "01v0x1n5inzd6pbr4zcwa40w3lz1mfrqhj01frwhp9c2ww3n9gwv"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "08072a78ba1157d106d305bdc93cd9c5d35bab98"
github_archive_nix_hash = "112370chh6vbiiiay20h7h5mdxwackxlqpvmq7s5d5l16c0mdzp7"

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "84975fdcacc8666e4571a4a447d78ddd0a9efcfc"
github_archive_nix_hash = "0wsprim79l6vfaaxg7plbrfdllhb6p5ra6wkl0hnmfqy7s6ndqx5"

[migen]
github_user = "m-labs"
github_repo = "migen"
git_revision = "0.9.2"
github_archive_nix_hash = "1kq11if64zj84gv4w1q7l16fp17xjxl2wv5hc9dibr1z3m1gy67l"

[pythondata-cpu-vexriscv]
version = "2021030800"
tarball_url = "https://github.com/lschuermann/litex-vexriscv-custom/releases/download/2021030800/generated.tar.gz"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "0e6809132b7a42d26fc148b2b5e54ede8d6021ab"
github_archive_nix_hash = "182m452iclahx1ipic0x7q4c9w33w6vfm9lz8zbx39zli9dg7l03"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"
github_archive_nix_hash = "06pz4zs8wizx1yp5sv07l9gs71brlr4c8jrxszp0jq7h2g35zyxk"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "da5ad1e992e1a61926ad513b6f88b3a16867b5b9"
github_archive_nix_hash = "0awqylqj11nkzashk3wlbjl8d8lx7a3lxaa304jrbgn6zr13x1xx"
