[litex]
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "aebef6593284170fafe2d48bd367b80cf4184ae1"

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "b3175e4a9cf500e7f8bba3d9aacc374cc56f306a"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "7acb2a8c1c1abda63496d422d093dc6bbfe135a8"

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "17c19de8f858d04fd9a7e9c38eb04af636f2bea6"

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "9f118e83c819a20e1348d295cc9a251cc006f8f8"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "3d8ecdbcf9f0260292221ff63b0ad3f5e409a955"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "963165fc1a29073a7ac2218a970515253a95bbb8"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "08072a78ba1157d106d305bdc93cd9c5d35bab98"

[litesdcard]
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "0b4be6bd582de559e58d60b4a6a8590b818214ce"

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "05afb0cdf68991181f84a58f6e465433788ce39a"

[litevideo]
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "a345f6b52752eb51e2424125d16292d0a40e5ebc"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "0e6a58bf18b674981d6e24934ffd4c5809932845"

[pythondata-software-picolibc]
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "caf15a59b134588c6edaf04755b4d690bf81d233"

[valentyusb-hw_cdc_eptri]
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "912d8e6dc72d45e092e608ffcaabfeaaa6d4580f"
git_branch = "hw_cdc_eptri"
