[litex]
type = "github"
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "a6d9955c9d3065d5c04cd4cba392b2fcb831380f"

[litex-boards]
type = "github"
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "b8abdf1b39d322101e5ec88d0e0650b42f836a80"

[liteeth]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "97dccdb294fa2081536f26f4ef6235c004007432"

[litedram]
type = "github"
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "455305a3edc37ee764160344041a4018c7d5ebdd"

[litehyperbus]
type = "github"
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "76454e4c0c304a34b9915722de750887c3abbe89"

[liteiclink]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "1c70ba16477b2743d130051734f0e45e2053b7c4"

[litepcie]
type = "github"
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "ebb77b53fafd2d4718e3d307dc0b7bc56d12598b"

[litescope]
type = "github"
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "7105b474026383fff6e3c829e487b56754b6e380"

[litesdcard]
type = "github"
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "15955d88ad2390dfa46f4846f7fc22bd642738db"

[litespi]
type = "github"
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "63c815fe7c0c28b132a2407d836b7d8f80ea7a61"

[litevideo]
type = "github"
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-cpu-vexriscv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv"
git_revision = "e75700dff2ab9662f3e26dd89ab59a5f6da65687"

[pythondata-cpu-vexriscv_smp]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv_smp"
git_revision = "e8ce95bbff2742226e838a37a88e4153bd04178a"

[pythondata-misc-tapcfg]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "fbcb02422940bbb97c492f0c970959d262b33632"

[pythondata-software-compiler_rt]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "cdede3b5e35e0c8c385ff10d783905d95cd864ab"

[pythondata-software-picolibc]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "a5e11229885a87083ec54034f8d693ba52ea2718"

[valentyusb-hw_cdc_eptri]
type = "github"
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "0b534ccfccfcdcb7a5db219743f0c0b20e5ec412"
git_branch = "hw_cdc_eptri"
