[litex]
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "05b960d09bc7032adb97c404d28c1d7423a84d28"

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "67756e53ae0b039b78c904dee4c40ff667ab24cc"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "e39fec240b05f66f9592c24ea2c2aa7f5434efea"

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "e9a4a746e93af186695f00e72f035a7892e9212e"

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "9f118e83c819a20e1348d295cc9a251cc006f8f8"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "3d8ecdbcf9f0260292221ff63b0ad3f5e409a955"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "589815cb318ee15c7ce1422bd606e5b561a9d608"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "08072a78ba1157d106d305bdc93cd9c5d35bab98"

[litesdcard]
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "4edf05e627a8b5f03e632215accec8ab588737e3"

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "84975fdcacc8666e4571a4a447d78ddd0a9efcfc"

[litevideo]
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "0e6809132b7a42d26fc148b2b5e54ede8d6021ab"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "da5ad1e992e1a61926ad513b6f88b3a16867b5b9"

[valentyusb-hw_cdc_eptri]
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "912d8e6dc72d45e092e608ffcaabfeaaa6d4580f"
git_branch = "hw_cdc_eptri"
