[litex]
type = "github"
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "91fbc79ac2e0af4e9edf3a3fe423f98fb7bdeffb"

[litex-boards]
type = "github"
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "52f9f0f1079085fc7d09956b8d42ccb9a06357a5"

[liteeth]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "1ea28bd93a13bbadeccbab127738021b59e79009"

[litedram]
type = "github"
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "e9adaebf0ddc8468d28bffa8523f5a7dd048dfd5"

[litehyperbus]
type = "github"
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "76454e4c0c304a34b9915722de750887c3abbe89"

[liteiclink]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "030e96c23e89953e9f7808c3e2fcdb58c3dee133"

[litepcie]
type = "github"
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "8cd6081284fbc4bef01a6e84d75f2a2bb6e1c278"

[litescope]
type = "github"
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "976656b5194db2cdf6c3257c5975e4fa1233f859"

[litesdcard]
type = "github"
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "1e5595376ae0ad56bed0464bd5774cfc774220da"

[litespi]
type = "github"
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "a18df94acb70b155f839ae95c145122874aaabc3"

[litevideo]
type = "github"
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-cpu-vexriscv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv"
git_revision = "03d8c47e49872e3db7be5a9a04e7cd74021c41f1"

[pythondata-cpu-vexriscv_smp]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv_smp"
git_revision = "9da054f1d3aa73e20dfa570619e84e858fcb8687"

[pythondata-misc-tapcfg]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "fbcb02422940bbb97c492f0c970959d262b33632"

[pythondata-software-compiler_rt]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "cdede3b5e35e0c8c385ff10d783905d95cd864ab"

[pythondata-software-picolibc]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "a5e11229885a87083ec54034f8d693ba52ea2718"

[valentyusb-hw_cdc_eptri]
type = "github"
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "0b534ccfccfcdcb7a5db219743f0c0b20e5ec412"
git_branch = "hw_cdc_eptri"

[pythondata-misc-usb_ohci]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-usb_ohci"
git_revision = "1f9c77314d3b91fe3194245c3e3197a075803199"
